name: chat-app pipeline
on: [push]
jobs:
  install:
    name: install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install
      
runs:
  using: "composite"
  steps:
    - name: lint
      uses: borales/actions-yarn@v2.3.0
      with:
        cmd: lint
    - name: test
      uses: borales/actions-yarn@v2.3.0
      with:
        cmd: echo "test"
